# Generated by Django 4.2.2 on 2023-07-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTres', '0002_rename_entrgado_proovedor_entregado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='proovedor',
            name='entregado',
        ),
    ]
